export const options: any = {
  columns: [
    { width: 110, header: true },
    { width: 110 },
    { width: 110 },
    { width: 110 },
    { width: 110 },
    { width: 110 },
  ],
  rows: [
    { height: 28, header: true },
    { height: 25, header: true },
    { height: 25 },
    { height: 25 },
    { height: 25 },
    { height: 25 },
    { height: 23 },
  ],
  cells: [
    [{ colspan: 6, text: "1" }],
    [
      { text: "2" },
      { text: "3" },
      { colspan: 2, text: "4" },
      { text: "5" },
      { text: "6" },
    ],
    [
      { rowspan: 3, text: "7" },
      { text: "A" },
      { text: "B" },
      { text: "C" },
      { text: "D" },
      { text: "E" },
    ],
    [{ text: "F" }, { text: "G" }, { text: "H" }, { text: "I" }, { text: "K" }],
    [{ text: "L" }, { text: "M" }, { text: "N" }, { text: "O" }, { text: "P" }],
    [
      { rowspan: 2, text: "8" },
      { text: "Q" },
      { text: "R" },
      { text: "S" },
      { text: "T" },
      { text: "U" },
    ],
    [{ text: "V" }, { text: "W" }, { text: "X" }, { text: "Y" }, { text: "Z" }],
  ],
};
