name: action
on: [push, pull_request]
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_NAME: my-tights
        DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_SECRET
        docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG .
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
        docker tag $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USER/$IMAGE_NAME:latest
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest
    - name: deploy 
      uses: appleboy/ssh-action@v1.0.2
      env:
        DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
        IMAGE_NAME: my-tights
        SERVER_HOST: ${{ vars.SERVER_HOST }} 
        SERVER_USER: ${{ vars.SERVER_USER }}
        SERVER_PORT: ${{ vars.SERVER_PORT }}
      with:
        host: $SERVER_HOST
        username: $SERVER_USER
        password: ${{ secrets.SERVER_PWD }}
        port: $SERVER_PORT
        script: | 
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_SECRET
          docker rm -f $IMAGE_NAME
          docker pull $DOCKER_HUB_USER/$IMAGE_NAME:latest
          docker run -itd --name=$IMAGE_NAME -p 8000:8000 $DOCKER_HUB_USER/$IMAGE_NAME:latest
          docker ps

        
