# name: action
# on: [push, pull_request]
# jobs:
#   docker-image-build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2 # pull代码到运行服务器上
#     - name: Build Docker Image
#       env:
#         IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
#       run: |
#         docker build -t my-tights:$IMAGE_TAG .
        
        
name: action
on: [push, pull_request]
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_NAME: my-tights
        DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_SECRET
        docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG .
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
        docker tag $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USER/$IMAGE_NAME:latest
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest
