name: action
on: [push, pull_request]
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # pull代码到运行服务器上
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }} # 用于标记容器版本号
      run: |
        docker build -t my-tights:$IMAGE_TAG .
        
