name: action
on: [push, pull_request]
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
        IMAGE_NAME: my-tights
        DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      run: |
        docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_SECRET
        docker build -t $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG .
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG
        docker tag $DOCKER_HUB_USER/$IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USER/$IMAGE_NAME:latest
        docker push $DOCKER_HUB_USER/$IMAGE_NAME:latest
    - name: deploy 
      uses: appleboy/ssh-action@v1.0.2
      env:
        DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
        DOCKER_HUB_SECRET: ${{ secrets.DOCKER_HUB_SECRET }}
      with:
        host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
        username: ${{ secrets.SERVER_USER }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
        password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
        port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
        script: | # 重启更新镜像
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_SECRET
          docker rm -f test
          docker pull huziyin/blog-starter-kit:latest
          docker run -itd --name=test -p 3001:3000 huziyin/blog-starter-kit:latest
          docker ps

        
